In [1]:
import numpy as np

In [2]:
#1.How to concatenate two numpy arrays column-wise and row-wise?
array_1 = np.array([[1,2,3,4,5,6],
                  [7,8,9,10,11,12]])

In [3]:
array_1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [4]:
array_2 = np.array([[20,21,22,23,24,25],
                  [26,27,28,29,30,31]])

In [5]:
array_1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [6]:
np.concatenate((array_1,array_2),axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31]])

In [7]:
np.concatenate((array_1,array_2),axis=1)

array([[ 1,  2,  3,  4,  5,  6, 20, 21, 22, 23, 24, 25],
       [ 7,  8,  9, 10, 11, 12, 26, 27, 28, 29, 30, 31]])

In [8]:
#2.Consider the random number generation functions in NumPy generate a set of random numbers using the function rand.

a=np.random.rand(3)
a

array([0.1072332 , 0.45341194, 0.24154466])

In [9]:
#3.Create a 3D array of shape 5x3x2 to contain random decimal numbers between 5 and 10.

b=np.random.randint(5,10, size = (5,3,2))
b

array([[[9, 7],
        [6, 7],
        [9, 7]],

       [[6, 5],
        [7, 6],
        [5, 8]],

       [[8, 9],
        [7, 6],
        [9, 8]],

       [[7, 9],
        [8, 8],
        [9, 7]],

       [[8, 5],
        [8, 8],
        [7, 8]]])

In [10]:
# 4.Create a utility function to generate random arrays using def random_array() takes number of elements as one of the argument, and randint() from random library. 
import random    
def random_array(num):
    rand_num=random.sample(range(1,50),num)
    print(rand_num)
random_array(random.randint(1,10))   

[40, 25, 34, 12, 3, 27, 30, 11]


In [11]:
# 5.Create and Compute median using  Numpy function np.median()
import numpy as np
arr = [20,2,7,1,34]
print("the given array:",arr)
print("median:",np.median(arr))

the given array: [20, 2, 7, 1, 34]
median: 7.0


In [12]:
# 5.Create and Compute median using  Naive method using python
import statistics
arr = [20,2,7,1,34]
print("median:%s"%(statistics.median(arr)))

median:7


In [13]:
# 6.Create naive function to compute variance function, mean function using only python.
array_3 = [12,24,10,18,15]
variance=statistics.variance(array_3)
print("variance:",variance)

variance: 30.200000000000003


In [14]:
array_3 = [12,24,10,18,15]
variance=statistics.mean(array_3)
print("mean:",variance)

mean: 15.8


In [15]:
# 7.Convert a 1D array to a 2D array with 2 rows.
array_1d=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_2d=np.reshape(array_1d,(2,5))
print(array_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
# 8.How to stack two arrays vertically? Stack arrays A and B vertically?
import numpy as np
A = ([2,8,9,6])
B = ([4,6,7,1])
np.vstack((A,B))

array([[2, 8, 9, 6],
       [4, 6, 7, 1]])

In [17]:
# 9.Create a function using numpy to get the common items between two python numpy arrays?
arr_5=np.array([5,3,8,2,6,9])
arr_6=np.array([1,3,2,7,2,5])
np.intersect1d(arr_5,arr_6)

array([2, 3, 5])

In [18]:
# 10.Create a python function to get the positions where elements of two arrays match using Numpy function?
arr_5=np.array([5,3,8,2,6,9])
arr_6=np.array([1,3,2,7,2,9])
np.where(arr_5==arr_6)

(array([1, 5], dtype=int64),)

In [19]:
# 11.How to create a 2D array containing random floats between 5 and 10?
arr_7=np.random.uniform(5,10 , size = (2,2))
arr_7

array([[6.3954531 , 5.75303105],
       [6.14512545, 6.46428632]])

In [20]:
#12.Extract the text column species from the 1D iris imported using following url np.genfromtxt()
import pandas as pd
import numpy as np

In [21]:
iris_df = pd.read_csv("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv",sep=',', 
                     
                        header = 0)

In [22]:
iris_df 

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [23]:
txt_coloum = iris_df[['species']]
print(txt_coloum.head(10))

  species
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa
5  setosa
6  setosa
7  setosa
8  setosa
9  setosa


In [24]:
# 13.How to Convert the 1D iris to 2D array iris_2d by omitting the species column and dropping first row?
iris_data=iris_df .iloc[1: , :4]
iris_1d=np.array(iris_data)
iris_2d=iris_1d.reshape(149,4)
iris_2d

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3

In [25]:
# 14.How to compute the mean, median, standard deviation of a numpy array on the same iris dataset?
iris_df.agg(['mean' , 'median' ,'std'])

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.057333      3.758000     1.199333
median      5.800000     3.000000      4.350000     1.300000
std         0.828066     0.435866      1.765298     0.762238

In [26]:
# 16.Compute and Find the number and position of missing values in iris data’s sepal length column
iris_df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [27]:
#17.Drop rows that contain a missing value from a numpy array created by using iris dataset? 
iris_df.dropna()

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [28]:
# 15.How to scale an array so the values range exactly between 0 and 1 using Admission.csv?
Admission_df = pd.read_csv("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/Admission.csv",sep=',',
 
         header = 0)

In [29]:
Admission_df 

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [30]:
#15.How to scale an array so the values range exactly between 0 and 1 using Admission.csv?
add_data=Admission_df .values
def Normalize(data):
    return(data-np.min(data))/(np.max(data))-(np.min(data))
scale=Normalize(add_data)
scale

array([[0.002  , 0.674  , 0.236  , ..., 0.0193 , 0.002  , 0.00184],
       [0.004  , 0.648  , 0.214  , ..., 0.01774, 0.002  , 0.00152],
       [0.006  , 0.632  , 0.208  , ..., 0.016  , 0.002  , 0.00144],
       ...,
       [0.996  , 0.66   , 0.24   , ..., 0.01912, 0.002  , 0.00186],
       [0.998  , 0.624  , 0.206  , ..., 0.01686, 0.     , 0.00146],
       [1.     , 0.654  , 0.226  , ..., 0.01808, 0.     , 0.00168]])

In [31]:
#18.Sort the Admission dataset array based on TOEFL Score column and GRE Score. Use separate code for both. 

In [32]:
Admission_df ["TOEFL Score"].sort_values()

368     92
28      93
79      93
411     94
347     94
      ... 
81     120
97     120
297    120
143    120
497    120
Name: TOEFL Score, Length: 500, dtype: int64

In [33]:
Admission_df ["GRE Score"].sort_values()

377    290
117    290
168    293
79     294
272    294
      ... 
81     340
84     340
143    340
384    340
429    340
Name: GRE Score, Length: 500, dtype: int64

In [39]:
#19.Compute the Euclidean distance between two arrays using Numpy linalg?
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
dist = np.linalg.norm(array_1-array_2)
print(dist)


5.196152422706632


In [35]:
#20.Compute and Find the duplicate entries in the given Numpy array and mark them as True. Create 1-D array
a=np.array([2,3,4,5,6,3,5])
uniques = np.unique(a)
result = []
for i in a:
    if i not in uniques:
            result.append(True)
    else:
        result.append(False)
        uniques = np.delete(uniques, np.where(uniques == i))
print('Array: ', a)
result



Array:  [2 3 4 5 6 3 5]


[False, False, False, False, False, True, True]

In [36]:
#21.How to replace all missing values with 0, in a numpy array using Admission.csv and iris.csv?
a=Admission_df.isnull()
a

Serial No.  GRE Score  TOEFL Score  University Rating    SOP   LOR   \
0         False      False        False              False  False  False   
1         False      False        False              False  False  False   
2         False      False        False              False  False  False   
3         False      False        False              False  False  False   
4         False      False        False              False  False  False   
..          ...        ...          ...                ...    ...    ...   
495       False      False        False              False  False  False   
496       False      False        False              False  False  False   
497       False      False        False              False  False  False   
498       False      False        False              False  False  False   
499       False      False        False              False  False  False   

      CGPA  Research  Chance of Admit   
0    False     False             False  
1    False     False             False  
2    False     False             False  
3    False     False             False  
4    False     False             False  
..     ...       ...               ...  
495  False     False             False  
496  False     False             False  
497  False     False             False  
498  False     False             False  
499  False     False             False  

[500 rows x 9 columns]

In [37]:
a=iris_df.isnull()
a

sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]